require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  Include:
    - Guardfile
    - Rakefile  

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "Guardfile"

Layout/HeredocIndentation:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

    